---
sites:
  pmc:
    skip_provisioning: false
    repo: https://github.com/hauvong/custom-site-template.git
    hosts:
      - pmc.test
    custom:
#      share_code: true
      wp_type: single
      wp_tests: true
      wp_version: 5.4

  wpcom:
    skip_provisioning: false
    repo: https://github.com/hauvong/custom-site-template.git
    hosts:
      - wpcom.test
      - bgr.wpcom.test
      - pmc-corporate-2018.wpcom.test
      - pmc-deadline-2019.wpcom.test
      - pmc-footwearnews-2018.wpcom.test
      - pmc-hollywoodlife-2017.wpcom.test
      - pmc-spy.wpcom.test
      - pmc-summits.wpcom.test
      - pmc-summits-rr1.wpcom.test
      - pmc-summits-variety.wpcom.test
      - pmc-summits-wwd.wpcom.test
      - pmc-summits.wpcom.test
      - pmc-tvline.wpcom.test
      - pmc-variety-2017.wpcom.test
      - pmc-wwd-2016.wpcom.test
      - pmc-variety-2020.wpcom.test
    custom:
#      share_code: true
      wp_type: single
      wp_vip: classic
      wp_tests: true
      wp_version: 5.4

  vipgo:
    skip_provisioning: false
    repo: https://github.com/hauvong/custom-site-template.git
    hosts:
      - vipgo.test
      - rollingstone.vipgo.test
      - artnews.vipgo.test
      - goldderby.vipgo.test
      - sheknows.vipgo.test
      - soaps.vipgo.test
    custom:
#      share_code: true
      wp_type: single
      wp_vip: vipgo
      wp_tests: true
      wp_version: 5.4

utilities:
  core:
    - memcached-admin
#    - mongodb
    - opcache-status
    - php73
    - phpmyadmin
#    - tideways
    - tls-ca
    - webgrind

vm_config:
  cores: 4
  memory: 4096

general:
  db_backup: true
  db_restore: true
  db_share_type: false

vagrant-plugins:
  disksize: 10GB
