name: Check `config.yml`

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Read node version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install dependencies
        run: npm ci
      - name: Build config.yml
        run: npm run build
      - name: Confirm committed config.yml matches built version
        run: git diff --exit-code
